### ISSUE TITLE
vtl backend out of sync

### ISSUE THREAD

**Issue by derNarr** [paul-krug/VocalTractLab-Python#2]
Hi Paul,

the vtl backend is out of sync with the main branch on the vtl-dev github page, e. g. there is a `delete tube;` missing in `vtlClose`. What is the policy to sync the code?

Best, Tino

**Comment by paul-krug** [comment]
Hi Tino,

thank you for the comment. In the near future, the vtl backend directory in this repo will point to a certain tag of the vtl-dev main branch. Currently, it is out of sync indeed.

**Comment by paul-krug** [comment]
Was fixed since the backend is now accessed via vocaltractlab-cython which is in sync with VocalTractLabBackend-Dev
