### ISSUE TITLE
Installation fails on Windows 10

### ISSUE THREAD

**Issue by Simon-Stone** [paul-krug/VocalTractLab-Python#6]
When trying to install into a virtual environment using ``pip install vocaltractlab`` on a Windows 10 machine with MS Visual Studio 2019 installed, the installation fails (log attached).
[error.log](https://github.com/paul-krug/VocalTractLab-Python/files/8590180/error.log)

**Comment by nullpunktTUD** [comment]
Same error was reproduced on another Windows 10 machine.

**Comment by paul-krug** [comment]
FIxed
